In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## Setting



In [ ]:
!pip install geopandas

     |████████████████████████████████| 1.0 MB 5.1 MB/s 
     |████████████████████████████████| 16.7 MB 283 kB/s 
     |████████████████████████████████| 6.3 MB 46.5 MB/s 


In [ ]:
from os import listdir
from os.path import isfile, join
import pandas as pd
import geopandas as gpd
import time
import json
import folium
import matplotlib.pyplot as plt
%matplotlib inline

import numpy as np
import seaborn as sns
import fiona
from shapely.geometry.multipolygon import MultiPolygon
from shapely.geometry import Point, Polygon, LineString
from shapely import wkt

from tqdm import trange, tqdm, tqdm_notebook, tnrange

from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.preprocessing import Binarizer, MinMaxScaler
import sklearn.metrics as metrics
from lightgbm import LGBMClassifier
import xgboost as xgb

from imblearn.over_sampling import SMOTE
from functools import partial
#from bayes_opt import BayesianOptimization

from sklearn.feature_selection import SelectKBest, chi2
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix, accuracy_score

In [ ]:
pd.set_option('display.max_rows', 50)
pd.set_option('display.max_columns', 50)

## data 불러오기

In [ ]:
cd /content/drive/MyDrive/Colab Notebooks/22-1boaz/방학분석미니플젝/data_final

/content/drive/MyDrive/Colab Notebooks/22-1boaz/방학분석미니플젝/data_final


In [ ]:
train_fast = pd.read_csv('train_fast_final.csv')
test_fast = pd.read_csv('test_fast_final.csv')

train_slow = pd.read_csv('train_slow_final.csv')
test_slow = pd.read_csv('test_slow_final.csv')

In [ ]:
train_fast_X = train_fast.iloc[:, :-1]
train_fast_y = train_fast.iloc[:, -1]
test_fast_X = test_fast.iloc[:, :-1]
test_fast_y = test_fast.iloc[:, -1]

train_slow_X = train_slow.iloc[:, :-1]
train_slow_y = train_slow.iloc[:, -1]
test_slow_X = test_slow.iloc[:, :-1]
test_slow_y = test_slow.iloc[:, -1]

In [ ]:
 # (102316, 67) 급속
train_fast_X.shape, train_fast_y.shape, test_fast_X.shape, test_fast_y.shape

((102316, 67), (102316,), (25575, 67), (25575,))

In [ ]:
train_slow_X.shape, train_slow_y.shape, test_slow_X.shape, test_slow_y.shape

((102294, 67), (102294,), (25575, 67), (25575,))

## LightGBM 모델 적합

In [ ]:
lgbm_clf_fast = LGBMClassifier(n_jobs=-1)
lgbm_clf_slow = LGBMClassifier(n_jobs=-1)

In [ ]:
model_fast = [lgbm_clf_fast]
model_slow = [lgbm_clf_slow]

In [ ]:
for x in model_fast:
    x.fit(train_fast_X, train_fast_y)
for x in model_slow:
    x.fit(train_slow_X, train_slow_y)

## 성능평가

In [ ]:
thresholds = np.arange(0,1,0.1)

for x in model_fast:
    print(x)
    pred_proba=x.predict_proba(np.array(test_fast_X))
    pred_proba_1 = pred_proba[:,1].reshape(-1,1)
    for threshold in thresholds:
        binarizer = Binarizer(threshold=threshold)
        model_cl_pred = binarizer.transform(pred_proba_1)
        print('threshold : ', threshold)
        print('오차 행렬')
        confusion = confusion_matrix(test_fast_y,model_cl_pred)
        print(confusion)
        print('accuracy : ', accuracy_score(test_fast_y,model_cl_pred))
        print('precision : ', precision_score(test_fast_y,model_cl_pred))
        print('recall : ', recall_score(test_fast_y,model_cl_pred))
        print('f1_score : ', f1_score(test_fast_y,model_cl_pred))
        print('')
    print('===================================================')
    print('')

LGBMClassifier()
threshold :  0.0
오차 행렬
[[    0 25550]
 [    0    25]]
accuracy :  0.0009775171065493646
precision :  0.0009775171065493646
recall :  1.0
f1_score :  0.001953125

threshold :  0.1
오차 행렬
[[25534    16]
 [    6    19]]
accuracy :  0.9991397849462366
precision :  0.5428571428571428
recall :  0.76
f1_score :  0.6333333333333332

threshold :  0.2
오차 행렬
[[25536    14]
 [    7    18]]
accuracy :  0.9991788856304985
precision :  0.5625
recall :  0.72
f1_score :  0.631578947368421

threshold :  0.30000000000000004
오차 행렬
[[25539    11]
 [    8    17]]
accuracy :  0.9992570869990225
precision :  0.6071428571428571
recall :  0.68
f1_score :  0.6415094339622641

threshold :  0.4
오차 행렬
[[25540    10]
 [    8    17]]
accuracy :  0.9992961876832844
precision :  0.6296296296296297
recall :  0.68
f1_score :  0.6538461538461539

threshold :  0.5
오차 행렬
[[25543     7]
 [    9    16]]
accuracy :  0.9993743890518084
precision :  0.6956521739130435
recall :  0.64
f1_score :  0.6666666666666666

In [ ]:
thresholds = np.arange(0,1,0.1)

for x in model_slow:
    print(x)
    pred_proba=x.predict_proba(np.array(test_slow_X))
    pred_proba_1 = pred_proba[:,1].reshape(-1,1)
    for threshold in thresholds:
        binarizer = Binarizer(threshold=threshold)
        model_cl_pred = binarizer.transform(pred_proba_1)
        print('threshold : ', threshold)
        print('오차 행렬')
        confusion = confusion_matrix(test_slow_y,model_cl_pred)
        print(confusion)
        print('accuracy : ', accuracy_score(test_slow_y,model_cl_pred))
        print('precision : ', precision_score(test_slow_y,model_cl_pred))
        print('recall : ', recall_score(test_slow_y,model_cl_pred))
        print('f1_score : ', f1_score(test_slow_y,model_cl_pred))
        print('')
    print('===================================================')
    print('')

LGBMClassifier()
threshold :  0.0
오차 행렬
[[    0 25545]
 [    0    30]]
accuracy :  0.0011730205278592375
precision :  0.0011730205278592375
recall :  1.0
f1_score :  0.0023432923257176333

threshold :  0.1
오차 행렬
[[25520    25]
 [    1    29]]
accuracy :  0.9989833822091887
precision :  0.5370370370370371
recall :  0.9666666666666667
f1_score :  0.6904761904761905

threshold :  0.2
오차 행렬
[[25521    24]
 [    1    29]]
accuracy :  0.9990224828934506
precision :  0.5471698113207547
recall :  0.9666666666666667
f1_score :  0.6987951807228916

threshold :  0.30000000000000004
오차 행렬
[[25523    22]
 [    1    29]]
accuracy :  0.9991006842619746
precision :  0.5686274509803921
recall :  0.9666666666666667
f1_score :  0.7160493827160493

threshold :  0.4
오차 행렬
[[25527    18]
 [    2    28]]
accuracy :  0.9992179863147606
precision :  0.6086956521739131
recall :  0.9333333333333333
f1_score :  0.7368421052631579

threshold :  0.5
오차 행렬
[[25530    15]
 [    2    28]]
accuracy :  0.999335288367546

## Feature Importance - Permutation

In [ ]:
!pip install eli5

     |████████████████████████████████| 106 kB 5.4 MB/s 


In [ ]:
import eli5
from eli5.sklearn import PermutationImportance
from eli5.lightgbm import *
from eli5.sklearn import *

### 급속

In [ ]:
lgbm_fast = lgbm_clf_fast.fit(train_fast_X, train_fast_y)
perm = PermutationImportance(lgbm_fast, random_state=1).fit(test_fast_X, test_fast_y)
eli5.show_weights(perm, feature_names = test_fast_X.columns.tolist())

In [ ]:
print(eli5.format_as_text(explain_weights.explain_permutation_importance(perm, feature_names = test_fast_X.columns.tolist(), top=40)))

explain_weights.explain_permutation_importance(perm, feature_names = test_fast_X.columns.tolist(), top=70)

Explained as: feature importances

Feature importances, computed as a decrease in score when feature
values are permuted (i.e. become noise). This is also known as 
permutation importance.

If feature importances are computed on the same data as used for training, 
they don't reflect importance of features for generalization. Use a held-out
dataset if you want generalization feature importances.

0.0004 ± 0.0001  급속
0.0004 ± 0.0001  면적_scaled
0.0004 ± 0.0000  위락시설_scaled
0.0004 ± 0.0000  완속_scaled
0.0003 ± 0.0001  교육연구및복지시설_scaled
0.0002 ± 0.0002  주거지_scaled
0.0002 ± 0.0000  개발부지_scaled
0.0002 ± 0.0000  청소년관련시설_scaled
0.0001 ± 0.0001  공장_scaled
0.0001 ± 0.0001  버스
0.0001 ± 0.0001  busStation
0.0001 ± 0.0000  관광휴게시설_scaled
0.0001 ± 0.0001  창고_scaled
0.0001 ± 0.0000  전기차_scaled
0.0001 ± 0.0000  종교시설
0.0001 ± 0.0000  width_1
0.0001 ± 0.0001  dw_lanes_0
0.0001 ± 0.0000  체력증진시설
0.0000 ± 0.0000  자동차관련시설_scaled
0.0000 ± 0.0001  혼잡시간강도_scaled
0.0000 ± 0.0000  통신시설_scaled
0.0000 ± 0.0001  산업단지거

Explanation(estimator='PermutationImportance(estimator=LGBMClassifier(), random_state=1)', description="\nFeature importances, computed as a decrease in score when feature\nvalues are permuted (i.e. become noise). This is also known as \npermutation importance.\n\nIf feature importances are computed on the same data as used for training, \nthey don't reflect importance of features for generalization. Use a held-out\ndataset if you want generalization feature importances.\n", error=None, method='feature importances', is_regression=False, targets=None, feature_importances=FeatureImportances(importances=[FeatureWeight(feature='급속', weight=0.0003988269794721333, std=5.746603502129627e-05, value=None), FeatureWeight(feature='면적_scaled', weight=0.0003597262952101943, std=4.55988417974145e-05, value=None), FeatureWeight(feature='위락시설_scaled', weight=0.00035972629521017205, std=1.564027370477561e-05, value=None), FeatureWeight(feature='완속_scaled', weight=0.00035972629521017205, std=1.564027370477561e-05, value=None), FeatureWeight(feature='교육연구및복지시설_scaled', weight=0.0002502443792766318, std=3.128054740955122e-05, value=None), FeatureWeight(feature='주거지_scaled', weight=0.0002424242424242662, std=9.704534620519756e-05, value=None), FeatureWeight(feature='개발부지_scaled', weight=0.00018768328445750715, std=1.5640273704820015e-05, value=None), FeatureWeight(feature='청소년관련시설_scaled', weight=0.0001564027370478671, std=0.0, value=None), FeatureWeight(feature='공장_scaled', weight=0.0001251221896383159, std=6.727136083709134e-05, value=None), FeatureWeight(feature='관광휴게시설_scaled', weight=0.00011730205278592809, std=2.4729444067765422e-05, value=None), FeatureWeight(feature='busStation', weight=0.00011730205278592809, std=3.497271519058074e-05, value=None), FeatureWeight(feature='버스', weight=0.00011730205278592809, std=4.945888813560106e-05, value=None), FeatureWeight(feature='창고_scaled', weight=0.00010948191593351808, std=6.256109481918293e-05, value=None), FeatureWeight(feature='전기차_scaled', weight=8.602150537637688e-05, std=1.564027370477561e-05, value=None), FeatureWeight(feature='종교시설', weight=7.820136852398907e-05, std=0.0, value=None), FeatureWeight(feature='width_1', weight=7.820136852396687e-05, std=2.472944406780053e-05, value=None), FeatureWeight(feature='dw_lanes_0', weight=6.256109481914685e-05, std=3.128054740960118e-05, value=None), FeatureWeight(feature='체력증진시설', weight=5.474095796675904e-05, std=1.9155345007139047e-05, value=None), FeatureWeight(feature='자동차관련시설_scaled', weight=4.692082111434903e-05, std=1.5640273704820015e-05, value=None), FeatureWeight(feature='통신시설_scaled', weight=4.692082111434903e-05, std=1.5640273704820015e-05, value=None), FeatureWeight(feature='혼잡시간강도_scaled', weight=4.692082111434903e-05, std=3.83106900142101e-05, value=None), FeatureWeight(feature='산업단지거리_scaled', weight=3.9100684261983434e-05, std=3.497271519063039e-05, value=None), FeatureWeight(feature='dw_lanes_2', weight=3.910068426196123e-05, std=2.472944406780053e-05, value=None), FeatureWeight(feature='고도_scaled', weight=3.910068426196123e-05, std=2.472944406780053e-05, value=None), FeatureWeight(feature='dw_lanes_1', weight=3.910068426193902e-05, std=0.0, value=None), FeatureWeight(feature='차량수_scaled', weight=3.910068426193902e-05, std=0.0, value=None), FeatureWeight(feature='up_lanes_1', weight=3.910068426193902e-05, std=0.0, value=None), FeatureWeight(feature='dw_lanes_4', weight=3.910068426193902e-05, std=0.0, value=None), FeatureWeight(feature='업무시설_scaled', weight=3.910068426193902e-05, std=0.0, value=None), FeatureWeight(feature='계획부지_scaled', weight=3.910068426193902e-05, std=0.0, value=None), FeatureWeight(feature='공공시설_scaled', weight=3.910068426193902e-05, std=0.0, value=None), FeatureWeight(feature='공원_scaled', weight=3.910068426193902e-05, std=0.0, value=None), FeatureWeight(feature='학교_scaled', weight=3.128054740955122e-05, std=1.564027370477561e-05, value=None), FeatureWeight(feature='dw_lanes_3', weight=2.3460410557163413e-05, st

### 완속

In [ ]:
lgbm_slow = lgbm_clf_slow.fit(train_slow_X, train_slow_y)
perm = PermutationImportance(lgbm_slow, random_state=1).fit(test_slow_X, test_slow_y)
eli5.show_weights(perm, feature_names = test_slow_X.columns.tolist())

In [ ]:
print(eli5.format_as_text(explain_weights.explain_permutation_importance(perm, feature_names = test_slow_X.columns.tolist(), top=40)))

explain_weights.explain_permutation_importance(perm, feature_names = test_slow_X.columns.tolist(), top=70)

Explained as: feature importances

Feature importances, computed as a decrease in score when feature
values are permuted (i.e. become noise). This is also known as 
permutation importance.

If feature importances are computed on the same data as used for training, 
they don't reflect importance of features for generalization. Use a held-out
dataset if you want generalization feature importances.

0.0005 ± 0.0001  노유자시설_scaled
0.0005 ± 0.0001  숙박시설_scaled
0.0005 ± 0.0003  종교시설
0.0003 ± 0.0001  교육연구및복지시설_scaled
0.0002 ± 0.0001  width_5_scaled
0.0002 ± 0.0001  공공시설_scaled
0.0001 ± 0.0000  dw_lanes_3
0.0001 ± 0.0001  유원지
0.0001 ± 0.0000  주차장_scaled
0.0001 ± 0.0001  면적_scaled
0.0001 ± 0.0000  차량수_scaled
0.0001 ± 0.0000  혼잡빈도강도
0.0001 ± 0.0000  급속
0.0001 ± 0.0000  문화및집회시설_scaled
0.0001 ± 0.0000  창고_scaled
0.0001 ± 0.0002  화물차
0.0001 ± 0.0001  혼잡시간강도_scaled
0.0000 ± 0.0000  위락시설_scaled
0.0000 ± 0.0000  up_lanes_6_scaled
0.0000 ± 0.0000  학교_scaled
0.0000 ± 0.0000  운수시설_scaled
0.0000 ± 0.0001  

Explanation(estimator='PermutationImportance(estimator=LGBMClassifier(), random_state=1)', description="\nFeature importances, computed as a decrease in score when feature\nvalues are permuted (i.e. become noise). This is also known as \npermutation importance.\n\nIf feature importances are computed on the same data as used for training, \nthey don't reflect importance of features for generalization. Use a held-out\ndataset if you want generalization feature importances.\n", error=None, method='feature importances', is_regression=False, targets=None, feature_importances=FeatureImportances(importances=[FeatureWeight(feature='노유자시설_scaled', weight=0.0005395894428153136, std=7.167273814205854e-05, value=None), FeatureWeight(feature='숙박시설_scaled', weight=0.0004848484848485324, std=3.987503040933938e-05, value=None), FeatureWeight(feature='종교시설', weight=0.000461388074291369, std=0.00015522528438930347, value=None), FeatureWeight(feature='교육연구및복지시설_scaled', weight=0.00029716520039104746, std=3.987503040932631e-05, value=None), FeatureWeight(feature='width_5_scaled', weight=0.00021114369501467055, std=4.692082111437124e-05, value=None), FeatureWeight(feature='공공시설_scaled', weight=0.00017986314760514154, std=5.3038748646158144e-05, value=None), FeatureWeight(feature='dw_lanes_3', weight=0.00014076246334315812, std=1.9155345007139047e-05, value=None), FeatureWeight(feature='유원지', weight=0.0001329423264907703, std=3.128054740960118e-05, value=None), FeatureWeight(feature='주차장_scaled', weight=0.0001251221896383381, std=1.5640273704820015e-05, value=None), FeatureWeight(feature='면적_scaled', weight=0.00010948191593356249, std=2.9260272819355555e-05, value=None), FeatureWeight(feature='차량수_scaled', weight=0.00010948191593354028, std=1.564027370477561e-05, value=None), FeatureWeight(feature='혼잡빈도강도', weight=0.00010948191593354028, std=1.564027370477561e-05, value=None), FeatureWeight(feature='급속', weight=0.00010166177908115248, std=1.9155345007084654e-05, value=None), FeatureWeight(feature='문화및집회시설_scaled', weight=8.602150537637688e-05, std=1.564027370477561e-05, value=None), FeatureWeight(feature='창고_scaled', weight=7.820136852398907e-05, std=0.0, value=None), FeatureWeight(feature='화물차', weight=6.256109481921346e-05, std=8.051323668418414e-05, value=None), FeatureWeight(feature='혼잡시간강도_scaled', weight=6.256109481919125e-05, std=3.9875030409326316e-05, value=None), FeatureWeight(feature='위락시설_scaled', weight=3.9100684262050045e-05, std=0.0, value=None), FeatureWeight(feature='up_lanes_6_scaled', weight=3.9100684262050045e-05, std=0.0, value=None), FeatureWeight(feature='학교_scaled', weight=3.910068426202784e-05, std=2.472944406780053e-05, value=None), FeatureWeight(feature='busStation', weight=3.1280547409640036e-05, std=3.83106900142101e-05, value=None), FeatureWeight(feature='주거지_scaled', weight=3.1280547409640036e-05, std=1.5640273704820018e-05, value=None), FeatureWeight(feature='운수시설_scaled', weight=3.1280547409640036e-05, std=1.5640273704820015e-05, value=None), FeatureWeight(feature='장례식장_scaled', weight=2.3460410557230027e-05, std=3.9875030409339374e-05, value=None), FeatureWeight(feature='님비시설_scaled', weight=1.5640273704842224e-05, std=3.128054740960118e-05, value=None), FeatureWeight(feature='up_lanes_1', weight=1.5640273704820018e-05, std=1.9155345007139044e-05, value=None), FeatureWeight(feature='width_3', weight=7.820136852410009e-06, std=1.5640273704820015e-05, value=None), FeatureWeight(feature='청소년관련시설_scaled', weight=7.820136852410009e-06, std=1.5640273704820015e-05, value=None), FeatureWeight(feature='산업단지거리_scaled', weight=7.820136852410009e-06, std=1.5640273704820015e-05, value=None), FeatureWeight(feature='공원_scaled', weight=7.820136852410009e-06, std=1.5640273704820018e-05, value=None), FeatureWeight(feature='관광휴게시설_scaled', weight=2.2204460492503132e-17, std=2.472944406780053e-05, value=None), FeatureWeight(feature='묘지관련시설_scaled', weight=2.2204460492503132e-17, std=4.283265356834302e-05, value=None), FeatureWeight(fe

## Feature Importance

In [ ]:
fea_imp_ = pd.DataFrame({'cols':train_fast_X.columns, 'fea_imp':lgbm_clf_fast.feature_importances_})
fea_imp_.sort_values(by=['fea_imp'], ascending=True)

cols  fea_imp
44  dw_lanes_5_scaled        0
42  up_lanes_5_scaled        0
41  up_lanes_6_scaled        0
62                유원지        0
40     width_5_scaled        0
..                ...      ...
64             체력증진시설       97
8          주거지_scaled       98
59                 급속      135
25          면적_scaled      154
5           창고_scaled      166

[67 rows x 2 columns]

## Optuna

In [ ]:
!pip install optuna

     |████████████████████████████████| 308 kB 5.0 MB/s 
     |████████████████████████████████| 81 kB 9.5 MB/s 
     |████████████████████████████████| 210 kB 56.0 MB/s 
     |████████████████████████████████| 75 kB 4.3 MB/s 
     |████████████████████████████████| 49 kB 5.5 MB/s 
     |████████████████████████████████| 113 kB 43.8 MB/s 
     |████████████████████████████████| 150 kB 45.6 MB/s 
  Created wheel for pyperclip: filename=pyperclip-1.8.2-py3-none-any.whl size=11137 sha256=afd0d1ef0189cb7717add386b6c613995113e6d6ee5e40c150bed8d9e83a4625
  Stored in directory: /root/.cache/pip/wheels/9f/18/84/8f69f8b08169c7bae2dde6bd7daf0c19fca8c8e500ee620a28
Successfully built pyperclip


In [ ]:
import pandas as pd
import numpy as np
import optuna
from optuna import Trial, visualization
from optuna.samplers import TPESampler
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix

In [ ]:
X_fast_train = train_fast.iloc[:, :-1]
y_fast_train = train_fast.iloc[:, -1]
X_fast_test = test_fast.iloc[:, :-1]
y_fast_test = test_fast.iloc[:, -1]

X_slow_train = train_slow.iloc[:, :-1]
y_slow_train = train_slow.iloc[:, -1]
X_slow_test = test_slow.iloc[:, :-1]
y_slow_test = test_slow.iloc[:, -1]

[I 2022-02-25 08:21:41,264] Trial 5 finished with value: 0.8000000000000002 and parameters: {'learning_rate': 0.24126919501069777, 'n_estimators': 113, 'max_depth': 31, 'boosting': 'gbdt', 'feature_fraction': 0.8637387162156923, 'scale_pos_weight': 1.6314529692749955, 'num_leaves': 33, 'bagging_freq': 16, 'bagging_fraction': 0.8965246003392066, 'min_data_in_leaf': 890}. Best is trial 5 with value: 0.8000000000000002.

### 급속

In [ ]:
param = {'learning_rate': 0.24126919501069777, 'n_estimators': 113, 'max_depth': 31, 'boosting': 'gbdt',
         'feature_fraction': 0.8637387162156923, 'scale_pos_weight': 1.6314529692749955, 'num_leaves': 33, 'bagging_freq': 16,
         'bagging_fraction': 0.8965246003392066, 'min_data_in_leaf': 890,
         'objective':'binary', 'n_jobs':-1, 'random_state':42, 'subsample':1, 'metric':'binary_logloss'}

In [ ]:
optimized_LGBM_f = LGBMClassifier(**param)

In [ ]:
optimized_LGBM_f.fit(X_fast_train, y_fast_train)

LGBMClassifier(bagging_fraction=0.8965246003392066, bagging_freq=16,
               boosting='gbdt', feature_fraction=0.8637387162156923,
               learning_rate=0.24126919501069777, max_depth=31,
               metric='binary_logloss', min_data_in_leaf=890, n_estimators=113,
               num_leaves=33, objective='binary', random_state=42,
               scale_pos_weight=1.6314529692749955, subsample=1)

In [ ]:
y_fast_prob = optimized_LGBM_f.predict_proba(X_fast_test)

In [ ]:
y_fast_pred = optimized_LGBM_f.predict(X_fast_test)
f1_score(y_fast_test, y_fast_pred)

0.8000000000000002

In [ ]:
for threshold in range(1,10):
    threshold = round(threshold*0.1, 1)
    y_fast_pred = np.where(y_fast_prob>=threshold, 1, 0)
    print(f'{threshold} :{f1_score(y_fast_test, y_fast_pred[:,1])}')

0.1 :0.7407407407407408
0.2 :0.7843137254901961
0.3 :0.7843137254901961
0.4 :0.7843137254901961
0.5 :0.8000000000000002
0.6 :0.7755102040816326
0.7 :0.7916666666666667
0.8 :0.7916666666666667
0.9 :0.7391304347826089


### 완속

In [ ]:
param = {'learning_rate': 0.24126919501069777, 'n_estimators': 113, 'max_depth': 31,
         'boosting': 'gbdt', 'feature_fraction': 0.8637387162156923, 'scale_pos_weight': 1.6314529692749955,
         'num_leaves': 33, 'bagging_freq': 16, 'bagging_fraction': 0.8965246003392066, 'min_data_in_leaf': 890,
         'objective':'binary', 'n_jobs':-1, 'random_state':42, 'subsample':1, 'metric':'binary_logloss'}

In [ ]:
optimized_LGBM_s = LGBMClassifier(**param)

In [ ]:
optimized_LGBM_s.fit(X_slow_train, y_slow_train)

LGBMClassifier(bagging_fraction=0.8965246003392066, bagging_freq=16,
               boosting='gbdt', feature_fraction=0.8637387162156923,
               learning_rate=0.24126919501069777, max_depth=31,
               metric='binary_logloss', min_data_in_leaf=890, n_estimators=113,
               num_leaves=33, objective='binary', random_state=42,
               scale_pos_weight=1.6314529692749955, subsample=1)

In [ ]:
y_slow_prob = optimized_LGBM_s.predict_proba(X_slow_test)

In [ ]:
y_slow_pred = optimized_LGBM_s.predict(X_slow_test)
f1_score(y_slow_test, y_slow_pred)

0.767123287671233

In [ ]:
for threshold in range(1,10):
    threshold = round(threshold*0.1, 1)
    y_slow_pred = np.where(y_slow_prob>=threshold, 1, 0)
    print(f'{threshold} :{f1_score(y_slow_test, y_slow_pred[:,1])}')

0.1 :0.7435897435897435
0.2 :0.7435897435897435
0.3 :0.7466666666666667
0.4 :0.767123287671233
0.5 :0.767123287671233
0.6 :0.7777777777777778
0.7 :0.7887323943661972
0.8 :0.7887323943661972
0.9 :0.8


## SelectKBest - Optuna

### 급속

In [ ]:
ks = [10,15,20,25,30,35,40,45,50,55,60,65]

In [ ]:
for k in ks:
    fit = SelectKBest(chi2, k=k).fit(X_fast_train, y_fast_train)
    new_X_fast_train = fit.transform(X_fast_train)
    new_X_fast_test = fit.transform(X_fast_test)
    
    optimized_LGBM_f.fit(new_X_fast_train, y_fast_train)
    y_fast_prob = optimized_LGBM_f.predict_proba(new_X_fast_test)
    print(f'================================{k}================================')
    for threshold in range(1,10):
        threshold = round(threshold*0.1, 1)
        y_fast_pred = np.where(y_fast_prob>=threshold, 1, 0)
        print(f'{threshold} :{f1_score(y_fast_test, y_fast_pred[:,1])}')

================================10================================
0.1 :0.027201145311381535
0.2 :0.027377521613832854
0.3 :0.3564356435643564
0.4 :0.3636363636363637
0.5 :0.3655913978494624
0.6 :0.40963855421686746
0.7 :0.4266666666666667
0.8 :0.4444444444444445
0.9 :0.4193548387096775
================================15================================
0.1 :0.6666666666666666
0.2 :0.6666666666666666
0.3 :0.6909090909090909
0.4 :0.7037037037037037
0.5 :0.6792452830188679
0.6 :0.6923076923076923
0.7 :0.6938775510204083
0.8 :0.6938775510204083
0.9 :0.6666666666666666
================================20================================
0.1 :0.7037037037037037
0.2 :0.7450980392156863
0.3 :0.7450980392156863
0.4 :0.7346938775510204
0.5 :0.7346938775510204
0.6 :0.7346938775510204
0.7 :0.7346938775510204
0.8 :0.7659574468085107
0.9 :0.7659574468085107
================================25================================
0.1 :0.6122448979591836
0.2 :0.6122448979591836
0.3 :0.6382978723404256
0.4 :0.

* 최적 score = 0.7916666666666667
* 최적 k = 65
* 최적 threshold = 0.6, 0.7

### 완속

In [ ]:
for k in ks:
    fit = SelectKBest(chi2, k=k).fit(X_slow_train, y_slow_train)
    new_X_slow_train = fit.transform(X_slow_train)
    new_X_slow_test = fit.transform(X_slow_test)
    
    optimized_LGBM_s.fit(new_X_slow_train, y_slow_train)
    y_slow_prob = optimized_LGBM_s.predict_proba(new_X_slow_test)
    print(f'================================{k}================================')
    for threshold in range(1,10):
        threshold = round(threshold*0.1, 1)
        y_slow_pred = np.where(y_slow_prob>=threshold, 1, 0)
        print(f'{threshold} :{f1_score(y_slow_test, y_slow_pred[:,1])}')

================================10================================
0.1 :0.7142857142857143
0.2 :0.7499999999999999
0.3 :0.7499999999999999
0.4 :0.7179487179487181
0.5 :0.7012987012987012
0.6 :0.7027027027027029
0.7 :0.6478873239436621
0.8 :0.6470588235294117
0.9 :0.65625
================================15================================
0.1 :0.6987951807228916
0.2 :0.7088607594936709
0.3 :0.7088607594936709
0.4 :0.7272727272727273
0.5 :0.7466666666666667
0.6 :0.7567567567567568
0.7 :0.7887323943661972
0.8 :0.7536231884057971
0.9 :0.7076923076923077
================================20================================
0.1 :0.7272727272727273
0.2 :0.7567567567567568
0.3 :0.7567567567567568
0.4 :0.767123287671233
0.5 :0.767123287671233
0.6 :0.7887323943661972
0.7 :0.7714285714285714
0.8 :0.7941176470588235
0.9 :0.7301587301587302
================================25================================
0.1 :0.725
0.2 :0.7297297297297297
0.3 :0.7397260273972602
0.4 :0.75
0.5 :0.7323943661971831
0.6 

* 최적 score = 0.835820895522388
* 최적 k = 65
* 최적 threshold = 0.9



---

## SelectKBest - 기본

In [ ]:
LGBM_f = LGBMClassifier(n_jobs=-1)
LGBM_s = LGBMClassifier(n_jobs=-1)

### 급속

In [ ]:
for k in ks:
    fit = SelectKBest(chi2, k=k).fit(X_fast_train, y_fast_train)
    new_X_fast_train = fit.transform(X_fast_train)
    new_X_fast_test = fit.transform(X_fast_test)
    
    LGBM_f.fit(new_X_fast_train, y_fast_train)
    y_fast_prob = LGBM_f.predict_proba(new_X_fast_test)
    print(f'================================{k}================================')
    for threshold in range(1,10):
        threshold = round(threshold*0.1, 1)
        y_fast_pred = np.where(y_fast_prob>=threshold, 1, 0)
        print(f'{threshold} :{f1_score(y_fast_test, y_fast_pred[:,1])}')

================================10================================
0.1 :0.027835768963117603
0.2 :0.29508196721311475
0.3 :0.3148148148148148
0.4 :0.3207547169811321
0.5 :0.32
0.6 :0.34782608695652173
0.7 :0.36585365853658536
0.8 :0.33802816901408445
0.9 :0.3333333333333333
================================15================================
0.1 :0.5121951219512195
0.2 :0.6000000000000001
0.3 :0.6268656716417911
0.4 :0.6153846153846154
0.5 :0.625
0.6 :0.5806451612903226
0.7 :0.6101694915254237
0.8 :0.5925925925925927
0.9 :0.5217391304347826
================================20================================
0.1 :0.547945205479452
0.2 :0.5757575757575758
0.3 :0.59375
0.4 :0.576271186440678
0.5 :0.6415094339622641
0.6 :0.6415094339622641
0.7 :0.6122448979591836
0.8 :0.5957446808510639
0.9 :0.5581395348837209
================================25================================
0.1 :0.6176470588235294
0.2 :0.6885245901639344
0.3 :0.7142857142857142
0.4 :0.6538461538461539
0.5 :0.625000000000000

* 최적 score = 0.7169811320754718
* 최적 k = 40
* 최적 threshold = 0.5, 0.6

### 완속

In [ ]:
for k in ks:
    fit = SelectKBest(chi2, k=k).fit(X_slow_train, y_slow_train)
    new_X_slow_train = fit.transform(X_slow_train)
    new_X_slow_test = fit.transform(X_slow_test)
    
    LGBM_s.fit(new_X_slow_train, y_slow_train)
    y_slow_prob = LGBM_s.predict_proba(new_X_slow_test)
    print(f'================================{k}================================')
    for threshold in range(1,10):
        threshold = round(threshold*0.1, 1)
        y_slow_pred = np.where(y_slow_prob>=threshold, 1, 0)
        print(f'{threshold} :{f1_score(y_slow_test, y_slow_pred[:,1])}')

================================10================================
0.1 :0.5333333333333333
0.2 :0.5599999999999999
0.3 :0.6436781609195402
0.4 :0.6829268292682926
0.5 :0.6923076923076923
0.6 :0.7012987012987012
0.7 :0.6842105263157895
0.8 :0.6756756756756758
0.9 :0.676470588235294
================================15================================
0.1 :0.6060606060606061
0.2 :0.7058823529411764
0.3 :0.725
0.4 :0.7341772151898733
0.5 :0.7105263157894737
0.6 :0.7027027027027029
0.7 :0.6944444444444444
0.8 :0.7142857142857143
0.9 :0.7575757575757577
================================20================================
0.1 :0.6521739130434783
0.2 :0.6976744186046512
0.3 :0.6913580246913581
0.4 :0.6666666666666667
0.5 :0.684931506849315
0.6 :0.6857142857142857
0.7 :0.696969696969697
0.8 :0.6875
0.9 :0.631578947368421
================================25================================
0.1 :0.6511627906976745
0.2 :0.7179487179487181
0.3 :0.7105263157894737
0.4 :0.7297297297297297
0.5 :0.7397260273

* 최적 score = 0.7945205479452055
* 최적 k = 55
* 최적 threshold = 0.5

---

### SelectFromModel

In [ ]:
from sklearn.feature_selection SelectFromModel
lgbc=LGBMClassifier(**param)
embeded_lgb_selector = SelectFromModel(lgbc, max_features=featureCutoff)
embeded_lgb_selector.fit(X_slow_train, y_slow_train)