### 급속

### 급속
- f1 score 상위 3개 모델
  - XGB
  - Random forest
  - LightGBM


- 상위 모델 3개 앙상블

  - 0.7692307692307692

  - 0.7407407407407408

---
### `튜닝 X`

### 급속 상위 3개 모델 앙상블 (XGB, Random forest, LightGBM)

In [ ]:
!pip install scikit-learn

In [ ]:
import sklearn
sklearn.__version__
from sklearn.model_selection import cross_validate

In [ ]:
import pandas as pd

x_train = pd.read_csv("/content/drive/MyDrive/2022-1 BOAZ/모빌리티_미니 프로젝트/train_fast_final.csv").drop(['fast_exist'], axis=1)
y_train = pd.read_csv("/content/drive/MyDrive/2022-1 BOAZ/모빌리티_미니 프로젝트/train_fast_final.csv")['fast_exist'].values

In [ ]:
x_train.head(5)

혼잡시간강도_scaled  학교_scaled  편의시설_scaled  ...  체력증진시설    혼잡빈도강도       화물차
0       0.992165   0.208015          0.0  ...     0.0  0.007934  0.058462
1       0.900386   0.000000          0.0  ...     0.0  0.227802  0.059286
2       0.901190   0.000000          0.0  ...     0.0  0.213156  0.154903
3       1.000000   0.000000          0.0  ...     0.0  0.000000  0.001341
4       0.984552   0.000000          0.0  ...     0.0  0.024925  0.011695

[5 rows x 67 columns]

In [ ]:
y_train

array([0, 0, 0, ..., 1, 1, 1])

Voting - Soft vote

In [ ]:
x_test = pd.read_csv("/content/drive/MyDrive/2022-1 BOAZ/모빌리티_미니 프로젝트/test_fast_final.csv").drop(['fast_exist'], axis=1)
y_test = pd.read_csv("/content/drive/MyDrive/2022-1 BOAZ/모빌리티_미니 프로젝트/test_fast_final.csv")['fast_exist'].values

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, ExtraTreesClassifier, BaggingClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegressionCV, RidgeClassifier
# VotingClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import cross_validate

# ensemble 할 model 정의
models = [
    ('rfc', RandomForestClassifier()),
    ('xgb', XGBClassifier()),
    ('lgbm', LGBMClassifier()),
]

k_fold = 5

# hard vote
#hard_vote  = VotingClassifier(models, voting='hard')
#hard_vote_cv = cross_validate(hard_vote, x_train, y_train, cv=k_fold)
#hard_vote.fit(x_train, y_train)

# soft vote
soft_vote  = VotingClassifier(models, voting='soft')
soft_vote_cv = cross_validate(soft_vote, x_train, y_train, cv=k_fold)
soft_vote.fit(x_train, y_train)

VotingClassifier(estimators=[('rfc', RandomForestClassifier()),
                             ('xgb', XGBClassifier()),
                             ('lgbm', LGBMClassifier())],
                 voting='soft')

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
y_pred = soft_vote.predict(x_test)
print('f1 score:', f1_score(y_test, y_pred))
print('오차 행렬')
confusion_fast_val = confusion_matrix(y_test, y_pred)
print(confusion_fast_val)

f1 score: 0.6440677966101696
오차 행렬
[[25535    15]
 [    6    19]]


### 급속 상위 2개 모델 앙상블 (XGB, Random forest)

Voting - Soft vote

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, ExtraTreesClassifier, BaggingClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegressionCV, RidgeClassifier
# VotingClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import cross_validate

# ensemble 할 model 정의
models = [
    ('rfc', RandomForestClassifier()),
    ('xgb', XGBClassifier()),
]

k_fold = 5

# hard vote
#hard_vote  = VotingClassifier(models, voting='hard')
#hard_vote_cv = cross_validate(hard_vote, x_train, y_train, cv=k_fold)
#hard_vote.fit(x_train, y_train)

# soft vote
soft_vote  = VotingClassifier(models, voting='soft')
soft_vote_cv = cross_validate(soft_vote, x_train, y_train, cv=k_fold)
soft_vote.fit(x_train, y_train)

VotingClassifier(estimators=[('rfc', RandomForestClassifier()),
                             ('xgb', XGBClassifier())],
                 voting='soft')

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
y_pred = soft_vote.predict(x_test)
print('f1 score:', f1_score(y_test, y_pred))
print('오차 행렬')
confusion_fast_val = confusion_matrix(y_test, y_pred)
print(confusion_fast_val)

f1 score: 0.47058823529411764
오차 행렬
[[25510    40]
 [    5    20]]


---
### `튜닝 O`

### 급속 상위 3개 모델 앙상블 (XGB, Random forest, LightGBM)

XGB

In [ ]:
!pip install optuna

     |████████████████████████████████| 308 kB 4.3 MB/s 
     |████████████████████████████████| 81 kB 5.2 MB/s 
     |████████████████████████████████| 210 kB 8.0 MB/s 
     |████████████████████████████████| 75 kB 3.1 MB/s 
     |████████████████████████████████| 49 kB 4.4 MB/s 
     |████████████████████████████████| 150 kB 8.6 MB/s 
     |████████████████████████████████| 113 kB 8.6 MB/s 
  Created wheel for pyperclip: filename=pyperclip-1.8.2-py3-none-any.whl size=11137 sha256=fa4a839de4bc94062ced93715b3bccb7dc808b56cf4e17b7e1170a827bc5aa20
  Stored in directory: /root/.cache/pip/wheels/9f/18/84/8f69f8b08169c7bae2dde6bd7daf0c19fca8c8e500ee620a28
Successfully built pyperclip


In [ ]:
import pandas as pd
import numpy as np
from xgboost import XGBClassifier
import optuna
from optuna import Trial, visualization
from optuna.samplers import TPESampler
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix, accuracy_score

In [ ]:
import os, random # random seed 고정 
def set_seeds(seed): 
    os.environ['PYTHONHASHSEED'] = str(seed) 
    random.seed(seed) 
    np.random.seed(seed) 
    # tf.random.set_seed(seed) # Tensorflow 사용시 
    
SEED = 555
set_seeds(SEED)

LightGBM

In [ ]:
def LGBM_objective(trial):
    base_score = 0.5
    learning_rate = trial.suggest_float('learning_rate', 0, 1)
    n_estimators = trial.suggest_int('n_estimators', 100, 1000)
    max_depth = trial.suggest_int('max_depth', -1, 50)
    boosting = trial.suggest_categorical('boosting', ['rf', 'gbdt', 'dart']) # goss
    metric = 'binary_logloss'

    feature_fraction = trial.suggest_float('feature_fraction', 0.6, 0.9)
    scale_pos_weight = trial.suggest_float('scale_pos_weight', 1, 1.7)

    num_leaves = trial.suggest_int('num_leaves', 2, 40)
    bagging_freq = trial.suggest_int('bagging_freq', 1, 50)
    bagging_fraction = trial.suggest_float('bagging_fraction', 0.01, 0.99)
    min_data_in_leaf = trial.suggest_int('min_data_in_leaf', 50, 1000)

    n_jobs = -1
    random_state = 42
    objective = 'binary'
    subsample = 1
    # device='gpu'
    
   
    model = LGBMClassifier(base_score=base_score, boosting=boosting, learning_rate=learning_rate, max_depth=max_depth, n_jobs=n_jobs, random_state=random_state, subsample=subsample, 
                           n_estimators=n_estimators, metric=metric, feature_fraction=feature_fraction, scale_pos_weight=scale_pos_weight,
                           num_leaves=num_leaves, bagging_freq=bagging_freq, bagging_fraction=bagging_fraction, min_data_in_leaf=min_data_in_leaf,
                           objective=objective, 
                           # device=device
                          )

    model.fit(x_train, y_train)
    y_fast_pred = model.predict(x_test)
    f1 = f1_score(y_test, y_fast_pred)

    return f1
    
# Execute optuna and set hyperparameters
LGBM_study = optuna.create_study(direction='maximize')
LGBM_study.optimize(LGBM_objective, n_trials=5)

"""
# Create an instance with tuned hyperparameters
optimized_LGBM = LGBMClassifier(base_score=LGBM_study.best_params['base_score'], boosting=LGBM_study.best_params['boosting'], learning_rate=LGBM_study.best_params['learning_rate'],
                                max_depth=LGBM_study.best_params['max_depth'], n_estimators=LGBM_study.best_params['n_estimators'], feature_fraction=LGBM_study.best_params['feature_fraction'],
                                scale_pos_weight=LGBM_study.best_params['scale_pos_weight'], num_leaves=LGBM_study.best_params['num_leaves'], bagging_freq=LGBM_study.best_params['bagging_freq'],
                                bagging_fraction=LGBM_study.best_params['bagging_fraction'], min_data_in_leaf=LGBM_study.best_params['min_data_in_leaf'],
                                objective='binary', n_jobs=-1, random_state=42, subsample=1, metric='binary_logloss',
                                # device='gpu'
                               )"""

## result
# Create an instance with tuned hyperparameters
optimized_LGBM = LGBMClassifier(base_score=0.5, boosting=LGBM_study.best_params['boosting'], learning_rate=LGBM_study.best_params['learning_rate'],
                                max_depth=LGBM_study.best_params['max_depth'], n_estimators=LGBM_study.best_params['n_estimators'], feature_fraction=LGBM_study.best_params['feature_fraction'],
                                scale_pos_weight=LGBM_study.best_params['scale_pos_weight'], num_leaves=LGBM_study.best_params['num_leaves'], bagging_freq=LGBM_study.best_params['bagging_freq'],
                                bagging_fraction=LGBM_study.best_params['bagging_fraction'], min_data_in_leaf=LGBM_study.best_params['min_data_in_leaf'],
                                objective='binary', n_jobs=-1, random_state=42, subsample=1, metric='binary_logloss',
                                # device='gpu'
                               )

[I 2022-02-27 00:49:18,944] A new study created in memory with name: no-name-92b4930b-a411-4896-9148-7d5aaf839bca
[I 2022-02-27 00:49:36,759] Trial 0 finished with value: 0.0013572204125950054 and parameters: {'learning_rate': 0.8572552966618816, 'n_estimators': 571, 'max_depth': 13, 'boosting': 'dart', 'feature_fraction': 0.6492324330545682, 'scale_pos_weight': 1.326803313444988, 'num_leaves': 11, 'bagging_freq': 9, 'bagging_fraction': 0.32652842297331036, 'min_data_in_leaf': 851}. Best is trial 0 with value: 0.0013572204125950054.
[I 2022-02-27 00:49:48,928] Trial 1 finished with value: 0.05882352941176471 and parameters: {'learning_rate': 0.5927779050527254, 'n_estimators': 450, 'max_depth': 35, 'boosting': 'rf', 'feature_fraction': 0.6964493240284875, 'scale_pos_weight': 1.6772765258282276, 'num_leaves': 14, 'bagging_freq': 18, 'bagging_fraction': 0.7326589655643758, 'min_data_in_leaf': 808}. Best is trial 1 with value: 0.05882352941176471.
[I 2022-02-27 00:49:55,873] Trial 2 finis

Voting - Soft vote

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, ExtraTreesClassifier, BaggingClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegressionCV, RidgeClassifier
# VotingClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import cross_validate

# ensemble 할 model 정의
models = [
    ('rfc', RandomForestClassifier(random_state=25, n_estimators=31, 
                                   max_depth=2699, max_leaf_nodes=172,
                                   bootstrap = True, max_features = 'auto')),
    ('xgb', XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1,
              n_estimators=100, n_jobs=-1, num_parallel_tree=1, random_state=42,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1)),
    #('lgbm', LGBMClassifier()),
    ('lgbm', LGBMClassifier(base_score=0.5, boosting=LGBM_study.best_params['boosting'], learning_rate=LGBM_study.best_params['learning_rate'],
              max_depth=LGBM_study.best_params['max_depth'], n_estimators=LGBM_study.best_params['n_estimators'], 
              feature_fraction=LGBM_study.best_params['feature_fraction'], scale_pos_weight=LGBM_study.best_params['scale_pos_weight'],
              num_leaves=LGBM_study.best_params['num_leaves'], bagging_freq=LGBM_study.best_params['bagging_freq'],
              bagging_fraction=LGBM_study.best_params['bagging_fraction'], min_data_in_leaf=LGBM_study.best_params['min_data_in_leaf'],
              objective='binary', n_jobs=-1, random_state=42, subsample=1, metric='binary_logloss',
                                # device='gpu'
                               ))
]

k_fold = 5

# hard vote
#hard_vote  = VotingClassifier(models, voting='hard')
#hard_vote_cv = cross_validate(hard_vote, x_train, y_train, cv=k_fold)
#hard_vote.fit(x_train, y_train)

# soft vote
soft_vote  = VotingClassifier(models, voting='soft')
soft_vote_cv = cross_validate(soft_vote, x_train, y_train, cv=k_fold)
soft_vote.fit(x_train, y_train)

VotingClassifier(estimators=[('rfc',
                              RandomForestClassifier(max_depth=2699,
                                                     max_leaf_nodes=172,
                                                     n_estimators=31,
                                                     random_state=25)),
                             ('xgb',
                              XGBClassifier(interaction_constraints='',
                                            learning_rate=0.300000012,
                                            max_depth=6, n_jobs=-1,
                                            num_parallel_tree=1,
                                            random_state=42,
                                            tree_method='exact',
                                            validate_parameters=1)),
                             ('lgbm',
                              LGBMClassifier(bagging_fraction=0.7326589655643758,
                                             baggin

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
y_pred = soft_vote.predict(x_test)
print('f1 score:', f1_score(y_test, y_pred))
print('오차 행렬')
confusion_fast_val = confusion_matrix(y_test, y_pred)
print(confusion_fast_val)

f1 score: 0.7142857142857142
오차 행렬
[[25539    11]
 [    5    20]]


### 급속 상위 2개 모델 앙상블 (XGB, Random forest)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, ExtraTreesClassifier, BaggingClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegressionCV, RidgeClassifier
# VotingClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import cross_validate

# ensemble 할 model 정의
models = [
    ('rfc', RandomForestClassifier(random_state=25, n_estimators=31, 
                                   max_depth=2699, max_leaf_nodes=172,
                                   bootstrap = True, max_features = 'auto')),
    ('xgb', XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1,
              n_estimators=100, n_jobs=-1, num_parallel_tree=1, random_state=42,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1)),
]

k_fold = 5

# hard vote
#hard_vote  = VotingClassifier(models, voting='hard')
#hard_vote_cv = cross_validate(hard_vote, x_train, y_train, cv=k_fold)
#hard_vote.fit(x_train, y_train)

# soft vote
soft_vote  = VotingClassifier(models, voting='soft')
soft_vote_cv = cross_validate(soft_vote, x_train, y_train, cv=k_fold)
soft_vote.fit(x_train, y_train)

VotingClassifier(estimators=[('rfc',
                              RandomForestClassifier(max_depth=2699,
                                                     max_leaf_nodes=172,
                                                     n_estimators=31,
                                                     random_state=25)),
                             ('xgb',
                              XGBClassifier(interaction_constraints='',
                                            learning_rate=0.300000012,
                                            max_depth=6, n_jobs=-1,
                                            num_parallel_tree=1,
                                            random_state=42,
                                            tree_method='exact',
                                            validate_parameters=1))],
                 voting='soft')

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
y_pred = soft_vote.predict(x_test)
print('f1 score:', f1_score(y_test, y_pred))
print('오차 행렬')
confusion_fast_val = confusion_matrix(y_test, y_pred)
print(confusion_fast_val)

f1 score: 0.72
오차 행렬
[[25543     7]
 [    7    18]]


---
### `튜닝 O & feature select`

### 급속 상위 4개 모델 앙상블 (XGB, Random forest, LightGBM, AdaBoost)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, ExtraTreesClassifier, BaggingClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegressionCV, RidgeClassifier
# VotingClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import cross_validate

# 선정된 feature 35개 변수에 담기.
features_20 = ['편의시설_scaled', '청소년관련시설_scaled', '차량수_scaled', '주차장_scaled',
       '주거지_scaled', '전기차_scaled', '인구_scaled', '의료시설_scaled', '위락시설_scaled',
       '완속_scaled', '업무시설_scaled', '숙박시설_scaled', '면적_scaled', '노유자시설_scaled',
       '계획부지_scaled', 'taxiStation_scaled', 'busStation', 'dw_lanes_0',
       'dw_lanes_1', 'dw_lanes_2', 'dw_lanes_3', 'dw_lanes_4', 'up_lanes_1',
       'up_lanes_2', 'up_lanes_3', 'up_lanes_4', 'width_1', 'width_2',
       'width_3', 'width_4', '급속', '버스', '승용차', '체력증진시설', '화물차']

# ensemble 할 model 정의
base_model_fast = DecisionTreeClassifier(criterion='entropy',
                                            max_depth = 5)

models = [
    ('rfc', RandomForestClassifier(random_state=25, n_estimators=31, 
                                   max_depth=2699, max_leaf_nodes=172,
                                   bootstrap = True, max_features = 'auto')),
    ('xgb', XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1,
              n_estimators=100, n_jobs=-1, num_parallel_tree=1, random_state=42,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1)),
    ('lgbm', LGBMClassifier(base_score=0.5, boosting=LGBM_study.best_params['boosting'], learning_rate=LGBM_study.best_params['learning_rate'],
                                max_depth=LGBM_study.best_params['max_depth'], n_estimators=LGBM_study.best_params['n_estimators'], feature_fraction=LGBM_study.best_params['feature_fraction'],
                                scale_pos_weight=LGBM_study.best_params['scale_pos_weight'], num_leaves=LGBM_study.best_params['num_leaves'], bagging_freq=LGBM_study.best_params['bagging_freq'],
                                bagging_fraction=LGBM_study.best_params['bagging_fraction'], min_data_in_leaf=LGBM_study.best_params['min_data_in_leaf'],
                                objective='binary', n_jobs=-1, random_state=42, subsample=1, metric='binary_logloss',
                                # device='gpu'
                               )),
    ('ada', AdaBoostClassifier(base_estimator = base_model_fast,    ## default None -> DecisionTreeClassifier.
                                  n_estimators = 60,                ## 생성할 약한 학습기 개수 지정. **
                                  random_state = 10,                
                                  learning_rate = 0.01))
]

k_fold = 5

# soft vote
soft_vote  = VotingClassifier(models, voting='soft')
soft_vote_cv = cross_validate(soft_vote, x_train[features_20], y_train, cv=k_fold)
soft_vote.fit(x_train[features_20], y_train)

VotingClassifier(estimators=[('rfc',
                              RandomForestClassifier(max_depth=2699,
                                                     max_leaf_nodes=172,
                                                     n_estimators=31,
                                                     random_state=25)),
                             ('xgb',
                              XGBClassifier(interaction_constraints='',
                                            learning_rate=0.300000012,
                                            max_depth=6, n_jobs=-1,
                                            num_parallel_tree=1,
                                            random_state=42,
                                            tree_method='exact',
                                            validate_parameters=1)),
                             ('lgbm',
                              LGBMClassifier(bagging_fraction=0.73265...
                                             learning_rate=0

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
y_pred = soft_vote.predict(x_test[features_20])
print('f1 score:', f1_score(y_test, y_pred))
print('오차 행렬')
confusion_fast_val = confusion_matrix(y_test, y_pred)
print(confusion_fast_val)

f1 score: 0.6779661016949153
오차 행렬
[[25536    14]
 [    5    20]]


### 급속 상위 3개 모델 앙상블 (XGB, Random forest, LightGBM)

feature selecting 상위 35개

In [ ]:
## feature selecting with SelectKBest

# target과 가장 correlated 된 features 를 k개 고르기.
## f_regresison, SelectKBest 불러오기.
from sklearn.feature_selection import f_regression, SelectKBest
## selctor 정의하기.
selector = SelectKBest(score_func=f_regression, k=37)
## 학습데이터에 fit_transform 
X_train_selected = selector.fit_transform(x_train, y_train)
## 테스트 데이터는 transform
X_val_selected = selector.transform(x_test)
X_train_selected.shape, X_val_selected, X_val_selected.shape

/usr/local/lib/python3.7/dist-packages/sklearn/feature_selection/_univariate_selection.py:289: RuntimeWarning: invalid value encountered in true_divide
  correlation_coefficient /= X_norms


((102316, 37),
 array([[0.        , 0.11821125, 0.        , ..., 0.        , 0.        ,
         0.1788093 ],
        [0.        , 0.11821125, 0.        , ..., 0.        , 0.        ,
         0.05379737],
        [0.32969534, 0.27447803, 0.        , ..., 0.15384615, 0.05882353,
         0.19839759],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.11615561],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.00439365],
        [0.        , 0.79850371, 0.        , ..., 0.07692308, 0.11764706,
         0.13428158]]),
 (25575, 37))

In [ ]:
all_names = x_train.columns
## selector.get_support()
selected_mask = selector.get_support()
## 선택된 특성(변수)들
selected_names = all_names[selected_mask]
## 선택되지 않은 특성(변수)들
unselected_names = all_names[~selected_mask]
print('Selected names: ', selected_names)
print('Unselected names: ', unselected_names)

Selected names:  Index(['학교_scaled', '편의시설_scaled', '청소년관련시설_scaled', '차량수_scaled',
       '주차장_scaled', '주거지_scaled', '전기차_scaled', '인구_scaled', '의료시설_scaled',
       '위락시설_scaled', '완속_scaled', '업무시설_scaled', '숙박시설_scaled', '면적_scaled',
       '노유자시설_scaled', '계획부지_scaled', 'taxiStation_scaled', 'busStation',
       'dw_lanes_0', 'dw_lanes_1', 'dw_lanes_2', 'dw_lanes_3', 'dw_lanes_4',
       'up_lanes_1', 'up_lanes_2', 'up_lanes_3', 'up_lanes_4', 'width_1',
       'width_2', 'width_3', 'width_4', '급속', '버스', '승용차', '종교시설', '체력증진시설',
       '화물차'],
      dtype='object')
Unselected names:  Index(['혼잡시간강도_scaled', '통신시설_scaled', '창고_scaled', '장례식장_scaled',
       '자동차관련시설_scaled', '위험물저장시설_scaled', '운수시설_scaled', '상하수도및가스시설_scaled',
       '산업단지거리_scaled', '발전시설_scaled', '문화및집회시설_scaled', '묘지관련시설_scaled',
       '님비시설_scaled', '농축산업시설_scaled', '녹지_scaled', '교육연구및복지시설_scaled',
       '광장_scaled', '관광휴게시설_scaled', '공장_scaled', '공원_scaled', '공공시설_scaled',
       '고도_scaled', '개발제한구역비율_scal

In [ ]:
# 선정된 feature 35개 변수에 담기. (급속)
features_20 = ['학교_scaled', '편의시설_scaled', '청소년관련시설_scaled', '차량수_scaled',
       '주차장_scaled', '주거지_scaled', '전기차_scaled', '인구_scaled', '의료시설_scaled',
       '위락시설_scaled', '완속_scaled', '업무시설_scaled', '숙박시설_scaled', '면적_scaled',
       '노유자시설_scaled', '계획부지_scaled', 'taxiStation_scaled', 'busStation',
       'dw_lanes_0', 'dw_lanes_1', 'dw_lanes_2', 'dw_lanes_3', 'dw_lanes_4',
       'up_lanes_1', 'up_lanes_2', 'up_lanes_3', 'up_lanes_4', 'width_1',
       'width_2', 'width_3', 'width_4', '급속', '버스', '승용차', '종교시설', '체력증진시설',
       '화물차']

In [ ]:
def LGBM_objective(trial):
    base_score = 0.5
    learning_rate = trial.suggest_float('learning_rate', 0, 1)
    n_estimators = trial.suggest_int('n_estimators', 100, 1000)
    max_depth = trial.suggest_int('max_depth', -1, 50)
    boosting = trial.suggest_categorical('boosting', ['rf', 'gbdt', 'dart']) # goss
    metric = 'binary_logloss'

    feature_fraction = trial.suggest_float('feature_fraction', 0.6, 0.9)
    scale_pos_weight = trial.suggest_float('scale_pos_weight', 1, 1.7)

    num_leaves = trial.suggest_int('num_leaves', 2, 40)
    bagging_freq = trial.suggest_int('bagging_freq', 1, 50)
    bagging_fraction = trial.suggest_float('bagging_fraction', 0.01, 0.99)
    min_data_in_leaf = trial.suggest_int('min_data_in_leaf', 50, 1000)

    n_jobs = -1
    random_state = 42
    objective = 'binary'
    subsample = 1
    # device='gpu'
    
   
    model = LGBMClassifier(base_score=base_score, boosting=boosting, learning_rate=learning_rate, max_depth=max_depth, n_jobs=n_jobs, random_state=random_state, subsample=subsample, 
                           n_estimators=n_estimators, metric=metric, feature_fraction=feature_fraction, scale_pos_weight=scale_pos_weight,
                           num_leaves=num_leaves, bagging_freq=bagging_freq, bagging_fraction=bagging_fraction, min_data_in_leaf=min_data_in_leaf,
                           objective=objective, 
                           # device=device
                          )

    model.fit(x_train[features_20], y_train)
    y_fast_pred = model.predict(x_test[features_20])
    f1 = f1_score(y_test, y_fast_pred)

    return f1
    
# Execute optuna and set hyperparameters
LGBM_study = optuna.create_study(direction='maximize')
LGBM_study.optimize(LGBM_objective, n_trials=20)

"""
# Create an instance with tuned hyperparameters
optimized_LGBM = LGBMClassifier(base_score=LGBM_study.best_params['base_score'], boosting=LGBM_study.best_params['boosting'], learning_rate=LGBM_study.best_params['learning_rate'],
                                max_depth=LGBM_study.best_params['max_depth'], n_estimators=LGBM_study.best_params['n_estimators'], feature_fraction=LGBM_study.best_params['feature_fraction'],
                                scale_pos_weight=LGBM_study.best_params['scale_pos_weight'], num_leaves=LGBM_study.best_params['num_leaves'], bagging_freq=LGBM_study.best_params['bagging_freq'],
                                bagging_fraction=LGBM_study.best_params['bagging_fraction'], min_data_in_leaf=LGBM_study.best_params['min_data_in_leaf'],
                                objective='binary', n_jobs=-1, random_state=42, subsample=1, metric='binary_logloss',
                                # device='gpu'
                               )"""

## result
# Create an instance with tuned hyperparameters
optimized_LGBM = LGBMClassifier(base_score=0.5, boosting=LGBM_study.best_params['boosting'], learning_rate=LGBM_study.best_params['learning_rate'],
                                max_depth=LGBM_study.best_params['max_depth'], n_estimators=LGBM_study.best_params['n_estimators'], feature_fraction=LGBM_study.best_params['feature_fraction'],
                                scale_pos_weight=LGBM_study.best_params['scale_pos_weight'], num_leaves=LGBM_study.best_params['num_leaves'], bagging_freq=LGBM_study.best_params['bagging_freq'],
                                bagging_fraction=LGBM_study.best_params['bagging_fraction'], min_data_in_leaf=LGBM_study.best_params['min_data_in_leaf'],
                                objective='binary', n_jobs=-1, random_state=42, subsample=1, metric='binary_logloss',
                                # device='gpu'
                               )

[I 2022-02-27 05:22:06,023] A new study created in memory with name: no-name-ea97497e-1f12-47da-aeab-e77d2c1076d4
[I 2022-02-27 05:22:13,376] Trial 0 finished with value: 0.7307692307692308 and parameters: {'learning_rate': 0.262534842169447, 'n_estimators': 320, 'max_depth': 23, 'boosting': 'gbdt', 'feature_fraction': 0.6996092320477946, 'scale_pos_weight': 1.379447621879899, 'num_leaves': 13, 'bagging_freq': 28, 'bagging_fraction': 0.8754441570638312, 'min_data_in_leaf': 212}. Best is trial 0 with value: 0.7307692307692308.
[I 2022-02-27 05:22:22,262] Trial 1 finished with value: 0.5517241379310344 and parameters: {'learning_rate': 0.7521966930479397, 'n_estimators': 160, 'max_depth': 3, 'boosting': 'dart', 'feature_fraction': 0.7660595270393115, 'scale_pos_weight': 1.4714453357753885, 'num_leaves': 36, 'bagging_freq': 2, 'bagging_fraction': 0.812915838742902, 'min_data_in_leaf': 336}. Best is trial 0 with value: 0.7307692307692308.
[I 2022-02-27 05:22:52,452] Trial 2 finished with v

voting

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, ExtraTreesClassifier, BaggingClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegressionCV, RidgeClassifier
# VotingClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import cross_validate

# 선정된 feature 35개 변수에 담기.
"""
features_20 = ['편의시설_scaled', '청소년관련시설_scaled', '차량수_scaled', '주차장_scaled',
       '주거지_scaled', '전기차_scaled', '인구_scaled', '의료시설_scaled', '위락시설_scaled',
       '완속_scaled', '업무시설_scaled', '숙박시설_scaled', '면적_scaled', '노유자시설_scaled',
       '계획부지_scaled', 'taxiStation_scaled', 'busStation', 'dw_lanes_0',
       'dw_lanes_1', 'dw_lanes_2', 'dw_lanes_3', 'dw_lanes_4', 'up_lanes_1',
       'up_lanes_2', 'up_lanes_3', 'up_lanes_4', 'width_1', 'width_2',
       'width_3', 'width_4', '급속', '버스', '승용차', '체력증진시설', '화물차']"""

# ensemble 할 model 정의
models = [
    ('rfc', RandomForestClassifier(random_state=25, n_estimators=31, 
                                   max_depth=2699, max_leaf_nodes=172,
                                   bootstrap = True, max_features = 'auto')),
    ('xgb', XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1,
              n_estimators=100, n_jobs=-1, num_parallel_tree=1, random_state=42,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1)),
    ('lgbm', LGBMClassifier(base_score=0.5, boosting=LGBM_study.best_params['boosting'], learning_rate=LGBM_study.best_params['learning_rate'],
                                max_depth=LGBM_study.best_params['max_depth'], n_estimators=LGBM_study.best_params['n_estimators'], feature_fraction=LGBM_study.best_params['feature_fraction'],
                                scale_pos_weight=LGBM_study.best_params['scale_pos_weight'], num_leaves=LGBM_study.best_params['num_leaves'], bagging_freq=LGBM_study.best_params['bagging_freq'],
                                bagging_fraction=LGBM_study.best_params['bagging_fraction'], min_data_in_leaf=LGBM_study.best_params['min_data_in_leaf'],
                                objective='binary', n_jobs=-1, random_state=42, subsample=1, metric='binary_logloss',
                                # device='gpu'
                               )),
]

k_fold = 10

# soft vote
soft_vote  = VotingClassifier(models, voting='soft')
soft_vote_cv = cross_validate(soft_vote, x_train[features_20], y_train, cv=k_fold)
soft_vote.fit(x_train[features_20], y_train)

VotingClassifier(estimators=[('rfc',
                              RandomForestClassifier(max_depth=2699,
                                                     max_leaf_nodes=172,
                                                     n_estimators=31,
                                                     random_state=25)),
                             ('xgb',
                              XGBClassifier(interaction_constraints='',
                                            learning_rate=0.300000012,
                                            max_depth=6, n_jobs=-1,
                                            num_parallel_tree=1,
                                            random_state=42,
                                            tree_method='exact',
                                            validate_parameters=1)),
                             ('lgbm',
                              LGBMClassifier(bagging_fraction=0.6972924008706155,
                                             baggin

In [ ]:
## 10겹 교차 검증 & n_trial = 20 ## 37
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
y_pred = soft_vote.predict(x_test[features_20])
print('f1 score:', f1_score(y_test, y_pred))
print('오차 행렬')
confusion_fast_val = confusion_matrix(y_test, y_pred)
print(confusion_fast_val)

f1 score: 0.7692307692307692
오차 행렬
[[25543     7]
 [    5    20]]


In [ ]:
## 10겹 교차 검증 & n_trial = 20 ## 40
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
y_pred = soft_vote.predict(x_test[features_20])
print('f1 score:', f1_score(y_test, y_pred))
print('오차 행렬')
confusion_fast_val = confusion_matrix(y_test, y_pred)
print(confusion_fast_val)

f1 score: 0.7058823529411765
오차 행렬
[[25542     8]
 [    7    18]]


In [ ]:
## 10겹 교차 검증 & n_trial = 20 ## 35
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
y_pred = soft_vote.predict(x_test[features_20])
print('f1 score:', f1_score(y_test, y_pred))
print('오차 행렬')
confusion_fast_val = confusion_matrix(y_test, y_pred)
print(confusion_fast_val)

f1 score: 0.7346938775510204
오차 행렬
[[25544     6]
 [    7    18]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
y_pred = soft_vote.predict(x_test[features_20])
print('f1 score:', f1_score(y_test, y_pred))
print('오차 행렬')
confusion_fast_val = confusion_matrix(y_test, y_pred)
print(confusion_fast_val)

f1 score: 0.7407407407407408
오차 행렬
[[25541     9]
 [    5    20]]


### 급속 상위 2개 모델 앙상블 (XGB, Random forest)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, ExtraTreesClassifier, BaggingClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegressionCV, RidgeClassifier
# VotingClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import cross_validate

# 선정된 feature 35개 변수에 담기.
features_20 = ['편의시설_scaled', '청소년관련시설_scaled', '차량수_scaled', '주차장_scaled',
       '주거지_scaled', '전기차_scaled', '인구_scaled', '의료시설_scaled', '위락시설_scaled',
       '완속_scaled', '업무시설_scaled', '숙박시설_scaled', '면적_scaled', '노유자시설_scaled',
       '계획부지_scaled', 'taxiStation_scaled', 'busStation', 'dw_lanes_0',
       'dw_lanes_1', 'dw_lanes_2', 'dw_lanes_3', 'dw_lanes_4', 'up_lanes_1',
       'up_lanes_2', 'up_lanes_3', 'up_lanes_4', 'width_1', 'width_2',
       'width_3', 'width_4', '급속', '버스', '승용차', '체력증진시설', '화물차']

# ensemble 할 model 정의
models = [
    ('rfc', RandomForestClassifier(random_state=25, n_estimators=31, 
                                   max_depth=2699, max_leaf_nodes=172,
                                   bootstrap = True, max_features = 'auto')),
    ('xgb', XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1,
              n_estimators=100, n_jobs=-1, num_parallel_tree=1, random_state=42,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1)),
]

k_fold = 5

# soft vote
soft_vote  = VotingClassifier(models, voting='soft')
soft_vote_cv = cross_validate(soft_vote, x_train[features_20], y_train, cv=k_fold)
soft_vote.fit(x_train[features_20], y_train)

VotingClassifier(estimators=[('rfc',
                              RandomForestClassifier(max_depth=2699,
                                                     max_leaf_nodes=172,
                                                     n_estimators=31,
                                                     random_state=25)),
                             ('xgb',
                              XGBClassifier(interaction_constraints='',
                                            learning_rate=0.300000012,
                                            max_depth=6, n_jobs=-1,
                                            num_parallel_tree=1,
                                            random_state=42,
                                            tree_method='exact',
                                            validate_parameters=1))],
                 voting='soft')

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
y_pred = soft_vote.predict(x_test[features_20])
print('f1 score:', f1_score(y_test, y_pred))
print('오차 행렬')
confusion_fast_val = confusion_matrix(y_test, y_pred)
print(confusion_fast_val)

f1 score: 0.7058823529411765
오차 행렬
[[25542     8]
 [    7    18]]


---
---
### 완속

### 완속
- f1 score 상위 3개 모델

  - LightGBM
  - XGB
  - Random forest

- 상위 모델 3개 앙상블

  - 0.8
  - 0.7733333333333334

---
### **`튜닝 X`**

### 완속 상위 3개 모델 앙상블 (LightGBM, XGB, Random forest)

In [ ]:
import pandas as pd

x_train = pd.read_csv("/content/drive/MyDrive/2022-1 BOAZ/모빌리티_미니 프로젝트/train_slow_final.csv").drop(['slow_exist'], axis=1)
y_train = pd.read_csv("/content/drive/MyDrive/2022-1 BOAZ/모빌리티_미니 프로젝트/train_slow_final.csv")['slow_exist'].values

In [ ]:
x_test = pd.read_csv("/content/drive/MyDrive/2022-1 BOAZ/모빌리티_미니 프로젝트/test_slow_final.csv").drop(['slow_exist'], axis=1)
y_test = pd.read_csv("/content/drive/MyDrive/2022-1 BOAZ/모빌리티_미니 프로젝트/test_slow_final.csv")['slow_exist'].values

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, ExtraTreesClassifier, BaggingClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegressionCV, RidgeClassifier
# VotingClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import cross_validate

# ensemble 할 model 정의
models = [
    ('rfc', RandomForestClassifier()),
    ('xgb', XGBClassifier()),
    ('lgbm', LGBMClassifier()),
]

k_fold = 5

# hard vote
#hard_vote  = VotingClassifier(models, voting='hard')
#hard_vote_cv = cross_validate(hard_vote, x_train, y_train, cv=k_fold)
#hard_vote.fit(x_train, y_train)

# soft vote
soft_vote  = VotingClassifier(models, voting='soft')
soft_vote_cv = cross_validate(soft_vote, x_train, y_train, cv=k_fold)
soft_vote.fit(x_train, y_train)

VotingClassifier(estimators=[('rfc', RandomForestClassifier()),
                             ('xgb', XGBClassifier()),
                             ('lgbm', LGBMClassifier())],
                 voting='soft')

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
y_pred = soft_vote.predict(x_test)
print('f1 score:', f1_score(y_test, y_pred))
print('오차 행렬')
confusion_fast_val = confusion_matrix(y_test, y_pred)
print(confusion_fast_val)

f1 score: 0.6206896551724138
오차 행렬
[[25535    15]
 [    7    18]]


### 완속 상위 2개 모델 앙상블 (LightGBM, XGB)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, ExtraTreesClassifier, BaggingClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegressionCV, RidgeClassifier
# VotingClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import cross_validate

# ensemble 할 model 정의
models = [
    ('xgb', XGBClassifier()),
    ('lgbm', LGBMClassifier()),
]

k_fold = 5

# hard vote
#hard_vote  = VotingClassifier(models, voting='hard')
#hard_vote_cv = cross_validate(hard_vote, x_train, y_train, cv=k_fold)
#hard_vote.fit(x_train, y_train)

# soft vote
soft_vote  = VotingClassifier(models, voting='soft')
soft_vote_cv = cross_validate(soft_vote, x_train, y_train, cv=k_fold)
soft_vote.fit(x_train, y_train)

VotingClassifier(estimators=[('xgb', XGBClassifier()),
                             ('lgbm', LGBMClassifier())],
                 voting='soft')

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
y_pred = soft_vote.predict(x_test)
print('f1 score:', f1_score(y_test, y_pred))
print('오차 행렬')
confusion_fast_val = confusion_matrix(y_test, y_pred)
print(confusion_fast_val)

f1 score: 0.6511627906976745
오차 행렬
[[25517    28]
 [    2    28]]


---
### **`튜닝 O`**

### 완속 상위 3개 모델 앙상블 (LightGBM, XGB, Random forest)

In [ ]:
def LGBM_objective(trial):
    base_score = 0.5
    learning_rate = trial.suggest_float('learning_rate', 0, 1)
    n_estimators = trial.suggest_int('n_estimators', 100, 1000)
    max_depth = trial.suggest_int('max_depth', -1, 50)
    boosting = trial.suggest_categorical('boosting', ['rf', 'gbdt', 'dart']) # goss
    metric = 'binary_logloss'

    feature_fraction = trial.suggest_float('feature_fraction', 0.6, 0.9)
    scale_pos_weight = trial.suggest_float('scale_pos_weight', 1, 1.7)

    num_leaves = trial.suggest_int('num_leaves', 2, 40)
    bagging_freq = trial.suggest_int('bagging_freq', 1, 50)
    bagging_fraction = trial.suggest_float('bagging_fraction', 0.01, 0.99)
    min_data_in_leaf = trial.suggest_int('min_data_in_leaf', 50, 1000)

    n_jobs = -1
    random_state = 42
    objective = 'binary'
    subsample = 1
    # device='gpu'
    
   
    model = LGBMClassifier(base_score=base_score, boosting=boosting, learning_rate=learning_rate, max_depth=max_depth, n_jobs=n_jobs, random_state=random_state, subsample=subsample, 
                           n_estimators=n_estimators, metric=metric, feature_fraction=feature_fraction, scale_pos_weight=scale_pos_weight,
                           num_leaves=num_leaves, bagging_freq=bagging_freq, bagging_fraction=bagging_fraction, min_data_in_leaf=min_data_in_leaf,
                           objective=objective, 
                           # device=device
                          )

    model.fit(x_train, y_train)
    y_fast_pred = model.predict(x_test)
    f1 = f1_score(y_test, y_fast_pred)

    return f1
    
# Execute optuna and set hyperparameters
LGBM_study = optuna.create_study(direction='maximize')
LGBM_study.optimize(LGBM_objective, n_trials=5)

"""
# Create an instance with tuned hyperparameters
optimized_LGBM = LGBMClassifier(base_score=LGBM_study.best_params['base_score'], boosting=LGBM_study.best_params['boosting'], learning_rate=LGBM_study.best_params['learning_rate'],
                                max_depth=LGBM_study.best_params['max_depth'], n_estimators=LGBM_study.best_params['n_estimators'], feature_fraction=LGBM_study.best_params['feature_fraction'],
                                scale_pos_weight=LGBM_study.best_params['scale_pos_weight'], num_leaves=LGBM_study.best_params['num_leaves'], bagging_freq=LGBM_study.best_params['bagging_freq'],
                                bagging_fraction=LGBM_study.best_params['bagging_fraction'], min_data_in_leaf=LGBM_study.best_params['min_data_in_leaf'],
                                objective='binary', n_jobs=-1, random_state=42, subsample=1, metric='binary_logloss',
                                # device='gpu'
                               )"""

## result
# Create an instance with tuned hyperparameters
optimized_LGBM = LGBMClassifier(base_score=0.5, boosting=LGBM_study.best_params['boosting'], learning_rate=LGBM_study.best_params['learning_rate'],
                                max_depth=LGBM_study.best_params['max_depth'], n_estimators=LGBM_study.best_params['n_estimators'], feature_fraction=LGBM_study.best_params['feature_fraction'],
                                scale_pos_weight=LGBM_study.best_params['scale_pos_weight'], num_leaves=LGBM_study.best_params['num_leaves'], bagging_freq=LGBM_study.best_params['bagging_freq'],
                                bagging_fraction=LGBM_study.best_params['bagging_fraction'], min_data_in_leaf=LGBM_study.best_params['min_data_in_leaf'],
                                objective='binary', n_jobs=-1, random_state=42, subsample=1, metric='binary_logloss',
                                # device='gpu'
                               )

[I 2022-02-27 02:12:51,385] A new study created in memory with name: no-name-2db0730b-55e9-4903-8373-7999c96472ee
[I 2022-02-27 02:13:05,346] Trial 0 finished with value: 0.7105263157894737 and parameters: {'learning_rate': 0.5945600679289605, 'n_estimators': 177, 'max_depth': -1, 'boosting': 'dart', 'feature_fraction': 0.7237512903757533, 'scale_pos_weight': 1.3528181670976895, 'num_leaves': 11, 'bagging_freq': 22, 'bagging_fraction': 0.4781215041069854, 'min_data_in_leaf': 350}. Best is trial 0 with value: 0.7105263157894737.
[I 2022-02-27 02:13:16,070] Trial 1 finished with value: 0.07231920199501246 and parameters: {'learning_rate': 0.5747548302371779, 'n_estimators': 376, 'max_depth': 34, 'boosting': 'rf', 'feature_fraction': 0.8212257826057334, 'scale_pos_weight': 1.6073127590938716, 'num_leaves': 39, 'bagging_freq': 47, 'bagging_fraction': 0.403211519495333, 'min_data_in_leaf': 410}. Best is trial 0 with value: 0.7105263157894737.
[I 2022-02-27 02:14:16,466] Trial 2 finished wit

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, ExtraTreesClassifier, BaggingClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegressionCV, RidgeClassifier
# VotingClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import cross_validate

# ensemble 할 model 정의
models = [
    ('rfc', RandomForestClassifier(
        random_state=25, n_estimators=251, 
        max_depth=9043, max_leaf_nodes=7310,
        bootstrap = True, max_features = 'sqrt')),
    ('xgb', XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1,
              n_estimators=100, n_jobs=-1, num_parallel_tree=1, random_state=42,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1)),
    ('lgbm',LGBMClassifier(base_score=0.5, boosting=LGBM_study.best_params['boosting'], learning_rate=LGBM_study.best_params['learning_rate'],
                                max_depth=LGBM_study.best_params['max_depth'], n_estimators=LGBM_study.best_params['n_estimators'], feature_fraction=LGBM_study.best_params['feature_fraction'],
                                scale_pos_weight=LGBM_study.best_params['scale_pos_weight'], num_leaves=LGBM_study.best_params['num_leaves'], bagging_freq=LGBM_study.best_params['bagging_freq'],
                                bagging_fraction=LGBM_study.best_params['bagging_fraction'], min_data_in_leaf=LGBM_study.best_params['min_data_in_leaf'],
                                objective='binary', n_jobs=-1, random_state=42, subsample=1, metric='binary_logloss',
                                # device='gpu'
                               )),
]

k_fold = 5

# hard vote
#hard_vote  = VotingClassifier(models, voting='hard')
#hard_vote_cv = cross_validate(hard_vote, x_train, y_train, cv=k_fold)
#hard_vote.fit(x_train, y_train)

# soft vote
soft_vote = VotingClassifier(models, voting='soft')
soft_vote_cv = cross_validate(soft_vote, x_train, y_train, cv=k_fold)
soft_vote.fit(x_train, y_train)

VotingClassifier(estimators=[('rfc',
                              RandomForestClassifier(max_depth=9043,
                                                     max_features='sqrt',
                                                     max_leaf_nodes=7310,
                                                     n_estimators=251,
                                                     random_state=25)),
                             ('xgb',
                              XGBClassifier(interaction_constraints='',
                                            learning_rate=0.300000012,
                                            max_depth=6, n_jobs=-1,
                                            num_parallel_tree=1,
                                            random_state=42,
                                            tree_method='exact',
                                            validate_parameters=1)),
                             ('lgbm',
                              LGBMClassifier(bagging_frac

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
y_pred = soft_vote.predict(x_test)
print('f1 score:', f1_score(y_test, y_pred))
print('오차 행렬')
confusion_fast_val = confusion_matrix(y_test, y_pred)
print(confusion_fast_val)

f1 score: 0.7368421052631579
오차 행렬
[[25527    18]
 [    2    28]]


---
### **`튜닝 O & feature select`**

### 완속 상위 3개 모델 앙상블 (LightGBM, XGB, Random forest)

In [ ]:
## feature selecting with SelectKBest

# target과 가장 correlated 된 features 를 k개 고르기.
## f_regresison, SelectKBest 불러오기.
from sklearn.feature_selection import f_regression, SelectKBest
## selctor 정의하기.
selector = SelectKBest(score_func=f_regression, k=35)
## 학습데이터에 fit_transform 
X_train_selected = selector.fit_transform(x_train, y_train)
## 테스트 데이터는 transform
X_val_selected = selector.transform(x_test)
X_train_selected.shape, X_val_selected, X_val_selected.shape

/usr/local/lib/python3.7/dist-packages/sklearn/feature_selection/_univariate_selection.py:289: RuntimeWarning: invalid value encountered in true_divide
  correlation_coefficient /= X_norms


((102294, 35),
 array([[0.86773642, 0.        , 0.11821125, ..., 0.17391304, 0.22580645,
         0.        ],
        [0.77545396, 0.        , 0.11821125, ..., 0.        , 0.11290323,
         0.        ],
        [0.87572344, 0.32969534, 0.27447803, ..., 0.2173913 , 0.18548387,
         0.15384615],
        ...,
        [0.83459168, 0.        , 0.        , ..., 0.2173913 , 0.17741935,
         0.        ],
        [0.58301616, 0.        , 0.        , ..., 0.06521739, 0.        ,
         0.        ],
        [0.84573301, 0.        , 0.79850371, ..., 0.17391304, 0.23387097,
         0.07692308]]),
 (25575, 35))

In [ ]:
all_names = x_train.columns
## selector.get_support()
selected_mask = selector.get_support()
## 선택된 특성(변수)들
selected_names = all_names[selected_mask]
## 선택되지 않은 특성(변수)들
unselected_names = all_names[~selected_mask]
print('Selected names: ', selected_names)
print('Unselected names: ', unselected_names)

Selected names:  Index(['학교_scaled', '편의시설_scaled', '통신시설_scaled', '창고_scaled', '차량수_scaled',
       '주거지_scaled', '전기차_scaled', '장례식장_scaled', '자동차관련시설_scaled',
       '의료시설_scaled', '위험물저장시설_scaled', '위락시설_scaled', '완속_scaled',
       '숙박시설_scaled', '상하수도및가스시설_scaled', '산업단지거리_scaled', '발전시설_scaled',
       '면적_scaled', '노유자시설_scaled', '공장_scaled', 'up_lanes_6_scaled',
       'busStation', 'dw_lanes_0', 'dw_lanes_4', 'up_lanes_1', 'up_lanes_4',
       'width_1', 'width_2', 'width_3', 'width_4', '급속', '버스', '승용차', '유원지',
       '혼잡빈도강도'],
      dtype='object')
Unselected names:  Index(['혼잡시간강도_scaled', '청소년관련시설_scaled', '주차장_scaled', '인구_scaled',
       '운수시설_scaled', '업무시설_scaled', '문화및집회시설_scaled', '묘지관련시설_scaled',
       '님비시설_scaled', '농축산업시설_scaled', '녹지_scaled', '교육연구및복지시설_scaled',
       '광장_scaled', '관광휴게시설_scaled', '공원_scaled', '공공시설_scaled', '고도_scaled',
       '계획부지_scaled', '개발제한구역비율_scaled', '개발부지_scaled', 'width_5_scaled',
       'up_lanes_5_scaled', 'taxiStation_scaled'

In [ ]:
# 선정된 feature 35개 변수에 담기. (완속)
features_20 = ['학교_scaled', '편의시설_scaled', '통신시설_scaled', '창고_scaled', '차량수_scaled',
       '주거지_scaled', '전기차_scaled', '장례식장_scaled', '자동차관련시설_scaled',
       '의료시설_scaled', '위험물저장시설_scaled', '위락시설_scaled', '완속_scaled',
       '숙박시설_scaled', '상하수도및가스시설_scaled', '산업단지거리_scaled', '발전시설_scaled',
       '면적_scaled', '노유자시설_scaled', '공장_scaled', 'up_lanes_6_scaled',
       'busStation', 'dw_lanes_0', 'dw_lanes_4', 'up_lanes_1', 'up_lanes_4',
       'width_1', 'width_2', 'width_3', 'width_4', '급속', '버스', '승용차', '유원지',
       '혼잡빈도강도']

In [ ]:
def LGBM_objective(trial):
    base_score = 0.5
    learning_rate = trial.suggest_float('learning_rate', 0, 1)
    n_estimators = trial.suggest_int('n_estimators', 100, 1000)
    max_depth = trial.suggest_int('max_depth', -1, 50)
    boosting = trial.suggest_categorical('boosting', ['rf', 'gbdt', 'dart']) # goss
    metric = 'binary_logloss'

    feature_fraction = trial.suggest_float('feature_fraction', 0.6, 0.9)
    scale_pos_weight = trial.suggest_float('scale_pos_weight', 1, 1.7)

    num_leaves = trial.suggest_int('num_leaves', 2, 40)
    bagging_freq = trial.suggest_int('bagging_freq', 1, 50)
    bagging_fraction = trial.suggest_float('bagging_fraction', 0.01, 0.99)
    min_data_in_leaf = trial.suggest_int('min_data_in_leaf', 50, 1000)

    n_jobs = -1
    random_state = 42
    objective = 'binary'
    subsample = 1
    # device='gpu'
    
   
    model = LGBMClassifier(base_score=base_score, boosting=boosting, learning_rate=learning_rate, max_depth=max_depth, n_jobs=n_jobs, random_state=random_state, subsample=subsample, 
                           n_estimators=n_estimators, metric=metric, feature_fraction=feature_fraction, scale_pos_weight=scale_pos_weight,
                           num_leaves=num_leaves, bagging_freq=bagging_freq, bagging_fraction=bagging_fraction, min_data_in_leaf=min_data_in_leaf,
                           objective=objective, 
                           # device=device
                          )

    model.fit(x_train[features_20], y_train)
    y_fast_pred = model.predict(x_test[features_20])
    f1 = f1_score(y_test, y_fast_pred)

    return f1
    
# Execute optuna and set hyperparameters
LGBM_study = optuna.create_study(direction='maximize')
LGBM_study.optimize(LGBM_objective, n_trials=20)

"""
# Create an instance with tuned hyperparameters
optimized_LGBM = LGBMClassifier(base_score=LGBM_study.best_params['base_score'], boosting=LGBM_study.best_params['boosting'], learning_rate=LGBM_study.best_params['learning_rate'],
                                max_depth=LGBM_study.best_params['max_depth'], n_estimators=LGBM_study.best_params['n_estimators'], feature_fraction=LGBM_study.best_params['feature_fraction'],
                                scale_pos_weight=LGBM_study.best_params['scale_pos_weight'], num_leaves=LGBM_study.best_params['num_leaves'], bagging_freq=LGBM_study.best_params['bagging_freq'],
                                bagging_fraction=LGBM_study.best_params['bagging_fraction'], min_data_in_leaf=LGBM_study.best_params['min_data_in_leaf'],
                                objective='binary', n_jobs=-1, random_state=42, subsample=1, metric='binary_logloss',
                                # device='gpu'
                               )"""

## result
# Create an instance with tuned hyperparameters
optimized_LGBM = LGBMClassifier(base_score=0.5, boosting=LGBM_study.best_params['boosting'], learning_rate=LGBM_study.best_params['learning_rate'],
                                max_depth=LGBM_study.best_params['max_depth'], n_estimators=LGBM_study.best_params['n_estimators'], feature_fraction=LGBM_study.best_params['feature_fraction'],
                                scale_pos_weight=LGBM_study.best_params['scale_pos_weight'], num_leaves=LGBM_study.best_params['num_leaves'], bagging_freq=LGBM_study.best_params['bagging_freq'],
                                bagging_fraction=LGBM_study.best_params['bagging_fraction'], min_data_in_leaf=LGBM_study.best_params['min_data_in_leaf'],
                                objective='binary', n_jobs=-1, random_state=42, subsample=1, metric='binary_logloss',
                                # device='gpu'
                               )

[I 2022-02-27 03:50:31,570] A new study created in memory with name: no-name-bd342c3d-b25c-4199-9518-c9ead4457be8
[I 2022-02-27 03:50:37,349] Trial 0 finished with value: 0.016119032858028518 and parameters: {'learning_rate': 0.8277148047258132, 'n_estimators': 798, 'max_depth': 35, 'boosting': 'gbdt', 'feature_fraction': 0.6192877289257493, 'scale_pos_weight': 1.4897697473279217, 'num_leaves': 10, 'bagging_freq': 27, 'bagging_fraction': 0.06408471368517445, 'min_data_in_leaf': 496}. Best is trial 0 with value: 0.016119032858028518.
[I 2022-02-27 03:50:41,129] Trial 1 finished with value: 0.7160493827160493 and parameters: {'learning_rate': 0.25963181542348246, 'n_estimators': 127, 'max_depth': 31, 'boosting': 'gbdt', 'feature_fraction': 0.7214084356277692, 'scale_pos_weight': 1.375461763212237, 'num_leaves': 32, 'bagging_freq': 25, 'bagging_fraction': 0.5330729835172187, 'min_data_in_leaf': 375}. Best is trial 1 with value: 0.7160493827160493.
[I 2022-02-27 03:50:52,249] Trial 2 finis

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, ExtraTreesClassifier, BaggingClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegressionCV, RidgeClassifier
# VotingClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import cross_validate

# 선정된 feature 35개 변수에 담기.
features_20 = ['학교_scaled', '편의시설_scaled', '통신시설_scaled', '창고_scaled', '차량수_scaled',
       '주거지_scaled', '전기차_scaled', '장례식장_scaled', '자동차관련시설_scaled',
       '의료시설_scaled', '위험물저장시설_scaled', '위락시설_scaled', '완속_scaled',
       '숙박시설_scaled', '상하수도및가스시설_scaled', '산업단지거리_scaled', '발전시설_scaled',
       '면적_scaled', '노유자시설_scaled', '공장_scaled', 'up_lanes_6_scaled',
       'busStation', 'dw_lanes_0', 'dw_lanes_4', 'up_lanes_1', 'up_lanes_4',
       'width_1', 'width_2', 'width_3', 'width_4', '급속', '버스', '승용차', '유원지',
       '혼잡빈도강도']

# ensemble 할 model 정의
models = [
    ('rfc', RandomForestClassifier(random_state=25, n_estimators=31, 
                                   max_depth=2699, max_leaf_nodes=172,
                                   bootstrap = True, max_features = 'auto')),
    ('xgb', XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1,
              n_estimators=100, n_jobs=-1, num_parallel_tree=1, random_state=42,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1)),
    ('lgbm', LGBMClassifier(base_score=0.5, boosting=LGBM_study.best_params['boosting'], learning_rate=LGBM_study.best_params['learning_rate'],
                                max_depth=LGBM_study.best_params['max_depth'], n_estimators=LGBM_study.best_params['n_estimators'], feature_fraction=LGBM_study.best_params['feature_fraction'],
                                scale_pos_weight=LGBM_study.best_params['scale_pos_weight'], num_leaves=LGBM_study.best_params['num_leaves'], bagging_freq=LGBM_study.best_params['bagging_freq'],
                                bagging_fraction=LGBM_study.best_params['bagging_fraction'], min_data_in_leaf=LGBM_study.best_params['min_data_in_leaf'],
                                objective='binary', n_jobs=-1, random_state=42, subsample=1, metric='binary_logloss',
                                # device='gpu'
                               )),
]

k_fold = 10

# soft vote
soft_vote  = VotingClassifier(models, voting='soft')
soft_vote_cv = cross_validate(soft_vote, x_train[features_20], y_train, cv=k_fold)
soft_vote.fit(x_train[features_20], y_train)

VotingClassifier(estimators=[('rfc',
                              RandomForestClassifier(max_depth=2699,
                                                     max_leaf_nodes=172,
                                                     n_estimators=31,
                                                     random_state=25)),
                             ('xgb',
                              XGBClassifier(interaction_constraints='',
                                            learning_rate=0.300000012,
                                            max_depth=6, n_jobs=-1,
                                            num_parallel_tree=1,
                                            random_state=42,
                                            tree_method='exact',
                                            validate_parameters=1)),
                             ('lgbm',
                              LGBMClassifier(bagging_fraction=0.6598101604129585,
                                             baggin

In [ ]:
## 10겹 교차 검증 & n_trials = 20
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
y_pred = soft_vote.predict(x_test[features_20])
print('f1 score:', f1_score(y_test, y_pred))
print('오차 행렬')
confusion_fast_val = confusion_matrix(y_test, y_pred)
print(confusion_fast_val)

f1 score: 0.7733333333333334
오차 행렬
[[25529    16]
 [    1    29]]


In [ ]:
## 10겹 교차 검증 & n_trials = 30
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
y_pred = soft_vote.predict(x_test[features_20])
print('f1 score:', f1_score(y_test, y_pred))
print('오차 행렬')
confusion_fast_val = confusion_matrix(y_test, y_pred)
print(confusion_fast_val)

f1 score: 0.8
오차 행렬
[[25533    12]
 [    2    28]]
